# Copyright (c) 2023 MASSA LABS <info@massa.net>

[package]
name = "massa_proto_bindings"
version = "0.1.0"
edition = "2021"
description = "Protobuf rust bindings for the Massa blockchain"
repository = "https://github.com/massalabs/massa-proto-bindings/"
homepage = "https://massa.net"
documentation = "https://docs.massa.net/"

[lib]
name = "massa_proto_bindings"

[dependencies]
prost = "0.11.8"
prost-types = "0.11.8"
tonic = "0.9.1"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.11.8"
tonic-build = "0.9.1"

[features]
build-tonic = []
